/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.programa;

import com.datos.Usuario;
import com.login.Login;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FontMetrics;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DAW104
 */
public class Principal1 extends javax.swing.JDialog {

    private Usuario user;

    /**
     * Creates new form Principal1
     */
    public Principal1(Usuario user) {
        initComponents();

        this.user = user;

        this.cerrarSesion.setText(" " + user.getNombre() + " " + user.getApellidos());
        // Limitar el tamaño del JLabel cerrarSesion
        FontMetrics metrics = cerrarSesion.getFontMetrics(cerrarSesion.getFont());
        int textWidth = metrics.stringWidth(cerrarSesion.getText());
        int textHeight = metrics.getHeight();
        Dimension preferredSize = new Dimension(textWidth, textHeight);
        cerrarSesion.setPreferredSize(preferredSize);
        cerrarSesion.setMaximumSize(preferredSize);

// Ajustar automáticamente el texto dentro del tamaño del JLabel cerrarSesion
        cerrarSesion.setHorizontalAlignment(JLabel.LEFT); // Ajustar el texto a la izquierda
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrarSesion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cargaDatos = new javax.swing.JPanel();
        imagenCargaDatos = new javax.swing.JLabel();
        textoCargaDatos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mantenimiento = new javax.swing.JPanel();
        imagenMantenimiento = new javax.swing.JLabel();
        textoMantenimiento = new javax.swing.JLabel();
        solicitud = new javax.swing.JPanel();
        imagenSolicitud = new javax.swing.JLabel();
        textoSolicitud = new javax.swing.JLabel();
        actividad = new javax.swing.JPanel();
        imagenActividad = new javax.swing.JLabel();
        textoActividad = new javax.swing.JLabel();

        cerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logout.png"))); // NOI18N
        cerrarSesion.setText("Cuenta");
        cerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        cargaDatos.setBackground(new java.awt.Color(51, 51, 51));
        cargaDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargaDatos.setPreferredSize(new java.awt.Dimension(90, 80));
        cargaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargaDatosMouseClicked(evt);
            }
        });

        imagenCargaDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cargaDatos.png"))); // NOI18N

        textoCargaDatos.setForeground(new java.awt.Color(255, 255, 255));
        textoCargaDatos.setText("Carga de datos");

        javax.swing.GroupLayout cargaDatosLayout = new javax.swing.GroupLayout(cargaDatos);
        cargaDatos.setLayout(cargaDatosLayout);
        cargaDatosLayout.setHorizontalGroup(
            cargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargaDatosLayout.createSequentialGroup()
                .addGroup(cargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cargaDatosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(imagenCargaDatos))
                    .addGroup(cargaDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textoCargaDatos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cargaDatosLayout.setVerticalGroup(
            cargaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargaDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenCargaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCargaDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Source Code Pro Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" ACEX");

        mantenimiento.setBackground(new java.awt.Color(40, 40, 40));
        mantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mantenimiento.setPreferredSize(new java.awt.Dimension(90, 80));
        mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mantenimientoMouseClicked(evt);
            }
        });

        imagenMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/mantenimiento.png"))); // NOI18N

        textoMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        textoMantenimiento.setText("Mantenimiento");

        javax.swing.GroupLayout mantenimientoLayout = new javax.swing.GroupLayout(mantenimiento);
        mantenimiento.setLayout(mantenimientoLayout);
        mantenimientoLayout.setHorizontalGroup(
            mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mantenimientoLayout.createSequentialGroup()
                .addGroup(mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mantenimientoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(imagenMantenimiento))
                    .addGroup(mantenimientoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textoMantenimiento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mantenimientoLayout.setVerticalGroup(
            mantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoMantenimiento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        solicitud.setBackground(new java.awt.Color(51, 51, 51));
        solicitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solicitud.setPreferredSize(new java.awt.Dimension(90, 80));
        solicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solicitudMouseClicked(evt);
            }
        });

        imagenSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/solicitud.png"))); // NOI18N

        textoSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        textoSolicitud.setText("Solicitud");

        javax.swing.GroupLayout solicitudLayout = new javax.swing.GroupLayout(solicitud);
        solicitud.setLayout(solicitudLayout);
        solicitudLayout.setHorizontalGroup(
            solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitudLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoSolicitud)
                    .addComponent(imagenSolicitud))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        solicitudLayout.setVerticalGroup(
            solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solicitudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoSolicitud)
                .addContainerGap())
        );

        actividad.setBackground(new java.awt.Color(51, 51, 51));
        actividad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actividad.setPreferredSize(new java.awt.Dimension(90, 80));
        actividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actividadMouseClicked(evt);
            }
        });

        imagenActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/actividad.png"))); // NOI18N

        textoActividad.setForeground(new java.awt.Color(255, 255, 255));
        textoActividad.setText("Actividad");

        javax.swing.GroupLayout actividadLayout = new javax.swing.GroupLayout(actividad);
        actividad.setLayout(actividadLayout);
        actividadLayout.setHorizontalGroup(
            actividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actividadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(actividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoActividad)
                    .addComponent(imagenActividad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actividadLayout.setVerticalGroup(
            actividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actividadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoActividad)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cargaDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(solicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(actividad, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseClicked
        String[] options = {"Cerrar", "Cancelar"};
        int choice = JOptionPane.showOptionDialog(this,
                "¿Estás seguro de que quieres cerrar sesión?",
                "Cerrar Sesión",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

        if (choice == 0) {
            dispose();
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_cerrarSesionMouseClicked

    private void cargaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargaDatosMouseClicked
        cargaDatos.setBackground(new Color(40, 40, 40));
        mantenimiento.setBackground(new Color(51, 51, 51));
        solicitud.setBackground(new Color(51, 51, 51));
        actividad.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_cargaDatosMouseClicked

    private void mantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mantenimientoMouseClicked
        cargaDatos.setBackground(new Color(51, 51, 51));
        mantenimiento.setBackground(new Color(40, 40, 40));
        solicitud.setBackground(new Color(51, 51, 51));
        actividad.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_mantenimientoMouseClicked

    private void solicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitudMouseClicked
        cargaDatos.setBackground(new Color(51, 51, 51));
        mantenimiento.setBackground(new Color(51, 51, 51));
        solicitud.setBackground(new Color(40, 40, 40));
        actividad.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_solicitudMouseClicked

    private void actividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actividadMouseClicked
        cargaDatos.setBackground(new Color(51, 51, 51));
        mantenimiento.setBackground(new Color(51, 51, 51));
        solicitud.setBackground(new Color(51, 51, 51));
        actividad.setBackground(new Color(40, 40, 40));
    }//GEN-LAST:event_actividadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actividad;
    private javax.swing.JPanel cargaDatos;
    private javax.swing.JLabel cerrarSesion;
    private javax.swing.JLabel imagenActividad;
    private javax.swing.JLabel imagenCargaDatos;
    private javax.swing.JLabel imagenMantenimiento;
    private javax.swing.JLabel imagenSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mantenimiento;
    private javax.swing.JPanel solicitud;
    private javax.swing.JLabel textoActividad;
    private javax.swing.JLabel textoCargaDatos;
    private javax.swing.JLabel textoMantenimiento;
    private javax.swing.JLabel textoSolicitud;
    // End of variables declaration//GEN-END:variables
}
